version: '3'
services:
    python3:
        restart: always
        build: .
        container_name: 'python3'
        working_dir: '/root/'
        # command: bash -c "chmod 777 /root/app/scripts/run.sh && /root/app/scripts/run.sh"
        tty: true
        volumes:
            - ./app:/root/app
        ports:
            - "8080:8080"